### ISSUE TITLE
Event Propergation

### ISSUE THREAD

**Issue by NoseBagUK** [dotmaster/Touchable-jQuery-Plugin#2]
Hi,

Not sure if this is the right place for this, not really an issue I don't think, I think I am doing something wrong. Just after a point in the right direction is possible. Great pluggin by the way.

My problem is that when I make a div Touchable() then I can no longer click on the links in the div.

I am using "touchablemove" event to do some custom scrolling of the div, which works great but then none of the links are clickable any more.

I am adding another event (longTap), but the target of the event object is the div not the link.

Anyway any help greatly appriciated.

Phil

**Comment by dotmaster** [comment]
Hi Phil,
could you post me your setup so I can reproduce the issue

thx

Gregor

**Comment by NoseBagUK** [comment]
Hi Gregor,

My setup is a lot more complicated but i get the same problem on this simple example..

http://nosebaguk.co.uk/demo/

As soon as the div becomes touchanble I can no longer click on the links.

Thanks for your help.

Phil

**Comment by dotmaster** [comment]
Hi Phil, which browser are you working on? I can reproduce your issue on iPad. I tried with IE8, Firefox, Chrome, Safari which works.
The reason for this lies in touchablemove being fired after 'touchstart', which on Mobile Safari will call preventDefault (thus stopping the default behaviour e.g. a click). The reason I do this, is that the default behaviour of touchstart on mobile safari is selecting an element, thus the element would get highlighted, which we don't want.
I have found out a way of not shallowing anchor hrefs though. The relevant change has no gone in version 0.0.3 of the plugin. So be sure to update your version to this one. You can see the relevant line from the diff, but for clarity it is:
        //don't shallow links, but all the rest
        if(!(e.currentTarget===self.$elem.get(0)))  e.preventDefault()

for your issue with the target on longTap, some Browsers (especially mobile ones) seem to loose or mixup the event info during event propagation, therefore the touch object carries two target informations, which I hadn't documented yet. Try to use touch.currentTarget instead of touch.target, and it should contain the info you need.

Let me know if this works for you

Regards

Gregor

**Comment by NoseBagUK** [comment]
Hi Gregor,

I am using Safari on iPad.

You fix works great, I have updated my demo and all seems well.

Thank you very much

Regards

Phil

**Comment by dotmaster** [comment]
Hi Phil, 
nice to hear everything works!
just to let you know, that I did another improvement yesterday, which should now also fix browsers, which don't communicate the event target correctly.
I now make use of document.elementFromPoint in such browsers to find out, what is the real target of the event (this affects all kind of mobile browseres afaik), so be sure to update to that.
You should also use document.elementFromPoint for your longTap issue, to find out the right element. I am sorry, but browsers have (again) real inconsistencies here.

Best regards

Gregor
